name: Main CD Frontend

on:
  workflow_call:
    inputs:
      node_version:
        type: string
        default: "16"

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
    name: Build Yarn Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install -g vsce

      - name: Authenticate with Personal Access Token
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
        run: vsce login jeancatarina -p $VSCE_PAT
      - name: Visual code generate package
        run: vsce package

  deploy:
    needs: [build]
    name: Deploy to visual studio marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Set AWS Creds
        run: vsce publish
